title = "Jonas Höckert"
baseURL = "https://jhockert.se/"
theme = "resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "github-dark"
enableGitInfo = false

[params]
address = "Europe/Stockholm"
email = "jonas@jhockert.se"
favicon = "/favicon.ico"
firstName = "Jonas"
lastName = "Höckert"
profileImage = "img/profile.jpeg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications =false
showQr = false
showCerts = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "G-SVZBR33RF8"

[[params.handles]]
link = "https://se.linkedin.com/in/jonas-hockert"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/xitobuh/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
